"""create equipment_safety table

Revision ID: ac01422aac18
Revises: f2217a6a7bdb
Create Date: 2025-10-08 00:58:15.722311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac01422aac18'
down_revision: Union[str, Sequence[str], None] = 'f2217a6a7bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_safety',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_safety_id'), 'equipment_safety', ['id'], unique=False)
    op.drop_index(op.f('ix_equipment_safety_records_id'), table_name='equipment_safety_records')
    op.drop_table('equipment_safety_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_safety_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_safety_records_id'), 'equipment_safety_records', ['id'], unique=False)
    op.drop_index(op.f('ix_equipment_safety_id'), table_name='equipment_safety')
    op.drop_table('equipment_safety')
    # ### end Alembic commands ###
